// Curated list of main-line English TCG booster packs (2002-2026),
// sourced from https://www.yugiohcardguide.com/yugioh-booster-packs.html and
// cross-referenced against YGOPRODeck's cardsets.php for exact set names,
// codes, and release dates. Excludes structure decks, starter decks, and
// most tins/collector sets that aren't randomized booster packs.
export const CURATED_BOOSTER_PACK_NAMES: string[] = [
  "Chaos Origins",
  "Battles of Legend: Glorious Gallery",
  "Blazing Dominion",
  "Rarity Collection 5",
  "Maze of Muertos",
  "Burst Protocol",
  "Phantom Revenge",
  "Doom of Dimensions",
  "2025 Mega-Pack Tin",
  "Justice Hunters",
  "Duelist's Advance",
  "Battles of Legend: Monster Mayhem",
  "Alliance Insight",
  "Quarter Century Stampede",
  "Maze of the Master",
  "Supreme Darkness",
  "Crossover Breakers",
  "Quarter Century Bonanza",
  "Rage of the Abyss",
  "25th Anniversary Tin: Dueling Mirrors",
  "The Infinite Forbidden",
  "Battles of Legend: Terminal Revenge",
  "25th Anniversary Rarity Collection II",
  "Legacy of Destruction",
  "Battles of Legend: Chapter 1",
  "Phantom Nightmare",
  "Maze of Millennia",
  "Valiant Smashers",
  "25th Anniversary Rarity Collection",
  "Age of Overlord",
  "25th Anniversary Tin: Dueling Heroes Mega Pack",
  "Legendary Duelists: Soulburning Volcano",
  "Duelist Nexus",
  "Battles of Legend: Monstrous Revenge",
  "Wild Survivors",
  "Cyberstorm Access",
  "Maze of Memories",
  "Photon Hypernova",
  "Amazing Defenders",
  "Battles of Legend: Crystal Revenge",
  "Darkwing Blast",
  "2022 Tin of the Pharaoh's Gods",
  "Tactical Masters",
  "Power of the Elements",
  "Legendary Duelists: Season 3",
  "Legendary Duelists: Duels From the Deep",
  "Dimension Force",
  "Ghosts From the Past: The 2nd Haunting",
  "Hidden Arsenal: Chapter 1",
  "Battle of Chaos",
  "The Grand Creators",
  "Brothers of Legend",
  "Burst of Destiny",
  "Legendary Duelists: Synchro Storm",
  "Dawn of Majesty",
  "King's Court",
  "Lightning Overdrive",
  "Ancient Guardians",
  "Ghosts From the Past",
  "Blazing Vortex",
  "Legendary Duelists: Season 2",
  "Genesis Impact",
  "Phantom Rage",
  "Legendary Duelists: Rage of Ra",
  "Dragons of Legend: The Complete Series",
  "Rise of the Duelist",
  "Battles of Legend: Armageddon",
  "Legendary Duelists: Season 1",
  "Toon Chaos",
  "Eternity Code",
  "Secret Slayers",
  "Duel Overload",
  "Ignition Assault",
  "Yu-Gi-Oh! The Dark Side of Dimensions Movie Pack Secret Edition",
  "Legendary Duelists: Magical Hero",
  "Speed Duel: Trials of the Kingdom",
  "Mystic Fighters",
  "Chaos Impact",
  "Legendary Duelists: Immortal Destiny",
  "Fists of the Gadgets",
  "Speed Duel: Scars of Battle",
  "Battles of Legend: Hero's Revenge",
  "Speed Duel: Attack from the Deep",
  "Dark Neostorm",
  "Speed Duel: Arena of Lost Souls",
  "The Infinity Chasers",
  "Savage Strike",
  "Legendary Duelists: Sisters of the Rose",
  "Hidden Summoners",
  "Soul Fusion",
  "Legendary Duelists: White Dragon Abyss",
  "Cybernetic Horizon",
  "Battles of Legend: Relentless Revenge",
  "Dark Saviors",
  "Flames of Destruction",
  "Star Pack VRAINS",
  "Legendary Duelists: Ancient Millennium",
  "Extreme Force",
  "Spirit Warriors",
  "Circuit Break",
  "Legendary Duelists",
  "Code of the Duelist",
  "Battles of Legend: Light's Revenge",
  "Pendulum Evolution",
  "Maximum Crisis",
  "Star Pack Battle Royal",
  "Fusion Enforcers",
  "Raging Tempest",
  "Destiny Soldiers",
  "Invasion: Vengeance",
  "Dragons of Legend: Unleashed",
  "The Dark Illusion",
  "Yu-Gi-Oh! The Dark Side of Dimensions Movie Pack",
  "Shining Victories",
  "Millennium Pack",
  "Wing Raiders",
  "Breakers of Shadow",
  "Dimension of Chaos",
  "High-Speed Riders",
  "Clash of Rebellions",
  "Dragons of Legend 2",
  "Star Pack ARC-V",
  "Crossed Souls",
  "World Superstars",
  "The Secret Forces",
  "Secrets of Eternity",
  "The New Challengers",
  "Duelist Alliance",
  "Battle Pack 3: Monster League",
  "Primal Origin",
  "Dragons of Legend",
  "Star Pack 2014",
  "Legacy of the Valiant",
  "War of the Giants: Round 2",
  "Shadow Specters",
  "Judgment of the Light",
  "Number Hunters",
  "Battle Pack 2: War of the Giants",
  "Lord of the Tachyon Galaxy",
  "Hidden Arsenal 7: Knight of Stars",
  "Star Pack 2013",
  "Cosmo Blazer",
  "Abyss Rising",
  "Return of the Duelist",
  "Hidden Arsenal 6: Omega Xyz",
  "Battle Pack: Epic Dawn",
  "Galactic Overlord",
  "Ra Yellow Mega Pack",
  "Order of Chaos",
  "Hidden Arsenal 5: Steelswarm Invasion",
  "Photon Shockwave",
  "Generation Force",
  "Extreme Victory",
  "Hidden Arsenal 4: Trishula's Triumph",
  "Yu-Gi-Oh! 3D Bonds Beyond Time Movie Pack",
  "Storm of Ragnarok",
  "Hidden Arsenal 3",
  "Starstrike Blast",
  "Duelist Revolution",
  "Hidden Arsenal 2",
  "The Shining Darkness",
  "Absolute Powerforce",
  "Stardust Overdrive",
  "Hidden Arsenal",
  "Ancient Prophecy",
  "Retro Pack 2",
  "Raging Battle",
  "Crimson Crisis",
  "Dark Legends",
  "Crossroads of Chaos",
  "The Duelist Genesis",
  "Premium Pack 2 (TCG)",
  "Retro Pack",
  "Light of Destruction",
  "Phantom Darkness",
  "Dark Revelation Volume 4",
  "Gladiator's Assault",
  "Tactical Evolution",
  "Premium Pack (TCG)",
  "Force of the Breaker",
  "Strike of Neos",
  "Dark Revelation Volume 3",
  "Cyberdark Impact",
  "Power of the Duelist",
  "Enemy of Justice",
  "Shadow of Infinity",
  "Elemental Energy",
  "Dark Revelation Volume 2",
  "Cybernetic Revolution",
  "Dark Beginning 2",
  "The Lost Millennium",
  "Dark Revelation Volume 1",
  "Flaming Eternity",
  "Rise of Destiny",
  "Dark Beginning 1",
  "Soul of the Duelist",
  "Ancient Sanctuary",
  "Invasion of Chaos",
  "Dark Crisis",
  "Magician's Force",
  "Pharaonic Guardian",
  "Legacy of Darkness",
  "Labyrinth of Nightmare",
  "Pharaoh's Servant",
  "Magic Ruler",
  "Metal Raiders",
  "Legend of Blue Eyes White Dragon",
];
