export interface PresetDeck {
  id: string;
  label: string;
  deckName: string;
  decklist: string;
}

// Based on the real 2002-2003 English TCG Starter Decks (Yugi/Kaiba/Joey/Pegasus),
// sourced from https://yugioh.fandom.com. Each original product shipped exactly
// 50 unique cards (no duplicates); these lists trim the 10 weakest/most
// generic filler cards from each to land on the modern 40-card deck minimum
// while keeping every card that defines the deck's identity and combos.
export const PRESET_DECKS: PresetDeck[] = [
  {
    id: "yugi",
    label: "Yugi Muto",
    deckName: "Yugi Muto Starter Deck",
    decklist: [
      "Mystical Elf",
      "Feral Imp",
      "Winged Dragon, Guardian of the Fortress #1",
      "Summoned Skull",
      "Beaver Warrior",
      "Dark Magician",
      "Gaia The Fierce Knight",
      "Curse of Dragon",
      "Celtic Guardian",
      "Giant Soldier of Stone",
      "Ansatsu",
      "Witty Phantom",
      "Ancient Elf",
      "Magical Ghost",
      "The Stern Mystic",
      "Wall of Illusion",
      "Neo the Magic Swordsman",
      "Baron of the Fiend Sword",
      "Sorcerer of the Doomed",
      "Trap Master",
      "Man-Eater Bug",
      "Sword of Dark Destruction",
      "Book of Secret Arts",
      "Dark Hole",
      "Dian Keto the Cure Master",
      "Fissure",
      "De-Spell",
      "Monster Reborn",
      "Change of Heart",
      "Last Will",
      "Soul Exchange",
      "Card Destruction",
      "Yami",
      "Remove Trap",
      "Trap Hole",
      "Two-Pronged Attack",
      "Reinforcements",
      "Waboku",
      "Dragon Capture Jar",
      "Ultimate Offering",
    ].join("\n"),
  },
  {
    id: "kaiba",
    label: "Seto Kaiba",
    deckName: "Seto Kaiba Starter Deck",
    decklist: [
      "Blue-Eyes White Dragon",
      "Hitotsu-Me Giant",
      "Ryu-Kishin",
      "The Wicked Worm Beast",
      "Battle Ox",
      "Koumori Dragon",
      "Judge Man",
      "Rogue Doll",
      "Uraby",
      "Gyakutenno Megami",
      "Ogre of the Black Shadow",
      "Dark Energy",
      "Invigoration",
      "Dark Hole",
      "Ookazi",
      "Ryu-Kishin Powered",
      "Swordstalker",
      "La Jinn the Mystical Genie of the Lamp",
      "Rude Kaiser",
      "Destroyer Golem",
      "D. Human",
      "Fissure",
      "Trap Hole",
      "Two-Pronged Attack",
      "De-Spell",
      "Monster Reborn",
      "The Inexperienced Spy",
      "Reinforcements",
      "Ancient Telescope",
      "Just Desserts",
      "Lord of D.",
      "The Flute of Summoning Dragon",
      "Mysterious Puppeteer",
      "Trap Master",
      "Sogen",
      "Hane-Hane",
      "Reverse Trap",
      "Remove Trap",
      "Castle Walls",
      "Ultimate Offering",
    ].join("\n"),
  },
  {
    id: "joey",
    label: "Joey Wheeler",
    deckName: "Joey Wheeler Starter Deck",
    decklist: [
      "Red-Eyes Black Dragon",
      "Swordsman of Landstar",
      "Baby Dragon",
      "Spirit of the Harp",
      "Flame Manipulator",
      "7 Colored Fish",
      "Sky Scout",
      "Gearfried the Iron Knight",
      "Karate Man",
      "Milus Radiant",
      "Time Wizard",
      "Maha Vailo",
      "Magician of Faith",
      "Sangan",
      "White Magical Hat",
      "Penguin Soldier",
      "Thousand Dragon",
      "Flame Swordsman",
      "Malevolent Nuzzler",
      "Dark Hole",
      "Dian Keto the Cure Master",
      "Fissure",
      "De-Spell",
      "Change of Heart",
      "Block Attack",
      "Giant Trunade",
      "The Reliable Guardian",
      "Remove Trap",
      "Monster Reborn",
      "Polymerization",
      "Mountain",
      "Dragon Treasure",
      "Shield & Sword",
      "Scapegoat",
      "Just Desserts",
      "Trap Hole",
      "Reinforcements",
      "Castle Walls",
      "Waboku",
      "Ultimate Offering",
      "Seven Tools of the Bandit",
      "Reverse Trap",
    ].join("\n"),
  },
  {
    id: "pegasus",
    label: "Maximillion Pegasus",
    deckName: "Maximillion Pegasus Starter Deck",
    decklist: [
      "Relinquished",
      "Giant Soldier of Stone",
      "Aqua Madoor",
      "Toon Alligator",
      "Hane-Hane",
      "Sonic Bird",
      "Mask of Darkness",
      "Witch of the Black Forest",
      "Man-Eater Bug",
      "Muka Muka",
      "Dream Clown",
      "Blue-Eyes Toon Dragon",
      "Toon Summoned Skull",
      "Manga Ryu-Ran",
      "Toon Mermaid",
      "Toon World",
      "Black Pendant",
      "Dark Hole",
      "Dian Keto the Cure Master",
      "Fissure",
      "De-Spell",
      "Change of Heart",
      "Stop Defense",
      "Mystical Space Typhoon",
      "Rush Recklessly",
      "Remove Trap",
      "Monster Reborn",
      "Soul Release",
      "Yami",
      "Black Illusion Ritual",
      "Ring of Magnetism",
      "Graceful Charity",
      "Trap Hole",
      "Reinforcements",
      "Castle Walls",
      "Waboku",
      "Seven Tools of the Bandit",
      "Ultimate Offering",
      "Magic Jammer",
      "Gryphon Wing",
    ].join("\n"),
  },
];
